INSERT INTO Authors (author_name) VALUES ('Brené Brown');
INSERT INTO Authors (author_name) VALUES ('Ryan Holliday');
INSERT INTO Authors (author_name) VALUES ('Harvard Business Review');
INSERT INTO Authors (author_name) VALUES ('Lars Schmidt');
INSERT INTO Authors (author_name) VALUES ('Robert Greene');
INSERT INTO Authors (author_name) VALUES ('Lawrence Freedman');
INSERT INTO Authors (author_name) VALUES ('Michael Bungay Stanier');
INSERT INTO Authors (author_name) VALUES ('Julie Zhuo');
INSERT INTO Authors (author_name) VALUES ('Josh Kaufman');
INSERT INTO Authors (author_name) VALUES ('Jorge Riechman');
INSERT INTO Authors (author_name) VALUES ('Erich Fromm');
INSERT INTO Authors (author_name) VALUES ('Daniel Goleman');
INSERT INTO Authors (author_name) VALUES ('Joe Navarro');
INSERT INTO Authors (author_name) VALUES ('Jeff Weiss');
INSERT INTO Authors (author_name) VALUES ('Amy Gallo');
INSERT INTO Authors (author_name) VALUES ('Karen Dillon');
INSERT INTO Authors (author_name) VALUES ('Max Tegmark');
INSERT INTO Authors (author_name) VALUES ('Caterina Kostoula');
INSERT INTO Authors (author_name) VALUES ('Chris Voss');
INSERT INTO Authors (author_name) VALUES ('Robert B. Cialdini');
INSERT INTO Authors (author_name) VALUES ('Dale Carnegie');
INSERT INTO Authors (author_name) VALUES ('Noah J. Goldstein');
INSERT INTO Authors (author_name) VALUES ('Steve J. Martin');
INSERT INTO Authors (author_name) VALUES ('Igor Ryzov');
INSERT INTO Authors (author_name) VALUES ('Vicenzo Venezia');
INSERT INTO Authors (author_name) VALUES ('Jessica Pryce-Jones');
INSERT INTO Authors (author_name) VALUES ('Rober Greene');
INSERT INTO Authors (author_name) VALUES ('Henry Kissinger');
INSERT INTO Authors (author_name) VALUES ('Simon Sinek');
INSERT INTO Authors (author_name) VALUES ('Daniil Maslyuk');
INSERT INTO Authors (author_name) VALUES ('Frank H. Netter');
INSERT INTO Authors (author_name) VALUES ('Edward C. Weber DO');
INSERT INTO Authors (author_name) VALUES ('Richard A. Jaffe');
INSERT INTO Authors (author_name) VALUES ('José Luis Velayos');
INSERT INTO Authors (author_name) VALUES ('G. Samama');
INSERT INTO Authors (author_name) VALUES ('Shirley M. Tighe');
INSERT INTO Authors (author_name) VALUES ('J.A.;GAL LOZANO');
INSERT INTO Authors (author_name) VALUES ('John Connell (Editor)');
INSERT INTO Authors (author_name) VALUES ('PIÉDROLA GIL');
INSERT INTO Authors (author_name) VALUES ('Jane C. Rothrock');
INSERT INTO Authors (author_name) VALUES ('Concepción Plaza Escribano');
INSERT INTO Authors (author_name) VALUES ('Francisco Javier Medina Domínguez');
INSERT INTO Authors (author_name) VALUES ('Jesús Hernández Gómez');
INSERT INTO Authors (author_name) VALUES ('Jesús Martínez Casillas');
INSERT INTO Authors (author_name) VALUES ('Juan José Martínez-Aedo Ollero');
INSERT INTO Authors (author_name) VALUES ('Pilar Castro Ortiz');
INSERT INTO Authors (author_name) VALUES ('Carol Mattson Porth');
INSERT INTO Authors (author_name) VALUES ('Marie Bretonnier');
INSERT INTO Authors (author_name) VALUES ('Emmanuel Godard');
INSERT INTO Authors (author_name) VALUES ('Philippe Liria');
INSERT INTO Authors (author_name) VALUES ('Jean Paul Sigé');
INSERT INTO Authors (author_name) VALUES ('Marion Mistichelli');
INSERT INTO Authors (author_name) VALUES ('Hermann Funk');
INSERT INTO Authors (author_name) VALUES ('Christina Kuhn');
INSERT INTO Authors (author_name) VALUES ('Silke Demme');
INSERT INTO Authors (author_name) VALUES ('Sabino Zubiaurre Cortés');
INSERT INTO Authors (author_name) VALUES ('Jesús María Arsuaga Ferreras');
INSERT INTO Authors (author_name) VALUES ('Benito Garzón Sánchez');
INSERT INTO Authors (author_name) VALUES ('Joanna Kotcher Fuller');
INSERT INTO Authors (author_name) VALUES ('ROBERT FRANK');
INSERT INTO Authors (author_name) VALUES ('BEN BERNANKE');
INSERT INTO Authors (author_name) VALUES ('Antonio Pardo Merino');
INSERT INTO Authors (author_name) VALUES ('Miguel Ángel Ruiz Díaz');
INSERT INTO Authors (author_name) VALUES ('Anthea Hatfield');
INSERT INTO Authors (author_name) VALUES ('Michael Tronson');
INSERT INTO Authors (author_name) VALUES ('J. Liébana Ureña');
INSERT INTO Authors (author_name) VALUES ('Joseph Hair');
INSERT INTO Authors (author_name) VALUES ('Ronald L. Tatham');
INSERT INTO Authors (author_name) VALUES ('Sarah Nettleton');
INSERT INTO Authors (author_name) VALUES ('Sabine Hossenfelder');
INSERT INTO Authors (author_name) VALUES ('Margaret J. Fehrenbach Charles A. Babbush');
INSERT INTO Authors (author_name) VALUES ('Dan L. Longo (editor)');
INSERT INTO Authors (author_name) VALUES ('M.D. Fauci');
INSERT INTO Authors (author_name) VALUES ('Anthony S. (Editor)');
INSERT INTO Authors (author_name) VALUES ('M.D. Kasper');
INSERT INTO Authors (author_name) VALUES ('Dennis L. (Editor)');
INSERT INTO Authors (author_name) VALUES ('M.d. Hauser');
INSERT INTO Authors (author_name) VALUES ('Stephen L. (Editor)');
INSERT INTO Authors (author_name) VALUES ('Ph.D. Jameson');
INSERT INTO Authors (author_name) VALUES ('J. Larry');
INSERT INTO Authors (author_name) VALUES ('M.D. (Editor)');
INSERT INTO Authors (author_name) VALUES ('Jeremy Harvey');
INSERT INTO Authors (author_name) VALUES ('Raymond Quivy');
INSERT INTO Authors (author_name) VALUES ('David Quammen');
INSERT INTO Authors (author_name) VALUES ('Lisa Randall');
INSERT INTO Authors (author_name) VALUES ('Alan Stern');
INSERT INTO Authors (author_name) VALUES ('David Grinspoon');
INSERT INTO Authors (author_name) VALUES ('Anthony Giddens');
INSERT INTO Authors (author_name) VALUES ('Karen Birdsall');
INSERT INTO Authors (author_name) VALUES ('J. de Echano');
INSERT INTO Authors (author_name) VALUES ('E. Martínez');
INSERT INTO Authors (author_name) VALUES ('P. Montarelo');
INSERT INTO Authors (author_name) VALUES ('L. Navlet');
INSERT INTO Authors (author_name) VALUES ('Pierre Bourdieu');
INSERT INTO Authors (author_name) VALUES ('Jean-Claude Passeron');
INSERT INTO Authors (author_name) VALUES ('Enrique Blanco García');
INSERT INTO Authors (author_name) VALUES ('Harold R. Kerbo');
INSERT INTO Authors (author_name) VALUES ('Julio Aróstegui Sánchez');
INSERT INTO Authors (author_name) VALUES ('Josep Maria Esquirol');
INSERT INTO Authors (author_name) VALUES ('Bernal Díaz del Castillo');
INSERT INTO Authors (author_name) VALUES ('Edward Gibbon');
INSERT INTO Authors (author_name) VALUES ('Alexis Jenni');
INSERT INTO Authors (author_name) VALUES ('Erving Goffman');
INSERT INTO Authors (author_name) VALUES ('Josep Alsinet');
INSERT INTO Authors (author_name) VALUES ('Clara Riba');
INSERT INTO Authors (author_name) VALUES ('Montserrat Ribera');
INSERT INTO Authors (author_name) VALUES ('Joan Subirats');
INSERT INTO Authors (author_name) VALUES ('Ignacio Sánchez-Cuenca');
INSERT INTO Authors (author_name) VALUES ('Thorstein Veblen');
INSERT INTO Authors (author_name) VALUES ('Martha Banta');
INSERT INTO Authors (author_name) VALUES ('Ralf Dahrendorf');
INSERT INTO Authors (author_name) VALUES ('Umberto Eco');
INSERT INTO Authors (author_name) VALUES ('Salvador Giner');
INSERT INTO Authors (author_name) VALUES ('Kottak');
INSERT INTO Authors (author_name) VALUES ('Diego Fusaro');
INSERT INTO Authors (author_name) VALUES ('Manuel Pérez Yruela');
INSERT INTO Authors (author_name) VALUES ('Jean-Yves Calvez');
INSERT INTO Authors (author_name) VALUES ('Anwar Shaikh');
INSERT INTO Authors (author_name) VALUES ('JANE I SANAHUJAM ANGELA ; GUITERAS');
INSERT INTO Authors (author_name) VALUES ('Various');
INSERT INTO Authors (author_name) VALUES ('Laura Tam');
INSERT INTO Authors (author_name) VALUES ('Josep Torras i Rodergas');
INSERT INTO Authors (author_name) VALUES ('Paulina Christensen');
INSERT INTO Authors (author_name) VALUES ('Anne Fox');
INSERT INTO Authors (author_name) VALUES ('Fyodor Dostoevsky');
INSERT INTO Authors (author_name) VALUES ('P.D. James');
INSERT INTO Authors (author_name) VALUES ('Silvia Castells Molina');
INSERT INTO Authors (author_name) VALUES ('Max Horkheimer');
INSERT INTO Authors (author_name) VALUES ('Theodor W. Adorno');
INSERT INTO Authors (author_name) VALUES ('Antonio Gramsci');
INSERT INTO Authors (author_name) VALUES ('Walter Benjamin');
INSERT INTO Authors (author_name) VALUES ('Daniel H. Pink');
INSERT INTO Authors (author_name) VALUES ('Jean-Paul Sartre');
INSERT INTO Authors (author_name) VALUES ('György Lukács');
INSERT INTO Authors (author_name) VALUES ('Thomas Piketty');
INSERT INTO Authors (author_name) VALUES ('Paul Lafargue');
INSERT INTO Authors (author_name) VALUES ('Ernesto Laclau');
INSERT INTO Authors (author_name) VALUES ('Chantal Mouffe');
INSERT INTO Authors (author_name) VALUES ('O.G. Sanchis');
INSERT INTO Authors (author_name) VALUES ('Joan E. Garcés');
INSERT INTO Authors (author_name) VALUES ('Louis Althusser');
INSERT INTO Authors (author_name) VALUES ('Vladimir Lenin');
INSERT INTO Authors (author_name) VALUES ('Rosa Luxemburg');
INSERT INTO Authors (author_name) VALUES ('Francisco Fernández Buey');
INSERT INTO Authors (author_name) VALUES ('Rubén Vega García');
INSERT INTO Authors (author_name) VALUES ('Donald Sassoon');
INSERT INTO Authors (author_name) VALUES ('G.A. Cohen');
INSERT INTO Authors (author_name) VALUES ('Daniel Kahneman');
INSERT INTO Authors (author_name) VALUES ('Jennifer Geary');
INSERT INTO Authors (author_name) VALUES ('Mario Amorós');
INSERT INTO Authors (author_name) VALUES ('Robert Service');
INSERT INTO Authors (author_name) VALUES ('José Luis Martín');
INSERT INTO Authors (author_name) VALUES ('David McLellan');
INSERT INTO Authors (author_name) VALUES ('Gustavo Vidal Manzanares');
INSERT INTO Authors (author_name) VALUES ('Georg Wilhelm Friedrich Hegel');
INSERT INTO Authors (author_name) VALUES ('Karl Marx');
INSERT INTO Authors (author_name) VALUES ('Andrés Saborit');
INSERT INTO Authors (author_name) VALUES ('Manuel Tuñón de Lara');
INSERT INTO Authors (author_name) VALUES ('Luis Sala González');
INSERT INTO Authors (author_name) VALUES ('Juan Pablo Fusi');
INSERT INTO Authors (author_name) VALUES ('Carme Cebrián');
INSERT INTO Authors (author_name) VALUES ('Jose del Barrio');
INSERT INTO Authors (author_name) VALUES ('John Rentoul');
INSERT INTO Authors (author_name) VALUES ('Isidre Molas');
INSERT INTO Authors (author_name) VALUES ('Manuel Alcántara; Antonia Martínez');
INSERT INTO Authors (author_name) VALUES ('Gabriel Jackson');
INSERT INTO Authors (author_name) VALUES ('Larousse');
INSERT INTO Authors (author_name) VALUES ('Paul Coggle');
INSERT INTO Authors (author_name) VALUES ('Heiner Schenke');
INSERT INTO Authors (author_name) VALUES ('Lydia Vellaccio');
INSERT INTO Authors (author_name) VALUES ('Bescherelle');
INSERT INTO Authors (author_name) VALUES ('Núria Benedito Pujol');
INSERT INTO Authors (author_name) VALUES ('Sebastián Trujillo Muñoz');
INSERT INTO Authors (author_name) VALUES ('Didier Fassin (Editor)');
INSERT INTO Authors (author_name) VALUES ('Dominique Memmi (Editor)');
INSERT INTO Authors (author_name) VALUES ('Xavier Bonal');
INSERT INTO Authors (author_name) VALUES ('Carlota Sole');
INSERT INTO Authors (author_name) VALUES ('Enrique Santamaria Lorenzo');
INSERT INTO Authors (author_name) VALUES ('Olga Solas Gaspar');
INSERT INTO Authors (author_name) VALUES ('Norbert Elias');
INSERT INTO Authors (author_name) VALUES ('Sònia Parella Rubio');
INSERT INTO Authors (author_name) VALUES ('Manuel Moreno Preciado');
INSERT INTO Authors (author_name) VALUES ('Susan Cain');
INSERT INTO Authors (author_name) VALUES ('Slavoj Zizek');
INSERT INTO Authors (author_name) VALUES ('Thomas Erikson');
INSERT INTO Authors (author_name) VALUES ('Richard Sennett');
INSERT INTO Authors (author_name) VALUES ('Hannah Arendt');
INSERT INTO Authors (author_name) VALUES ('Raúl Aguilar Cestero');
INSERT INTO Authors (author_name) VALUES ('Lynda Juall Carpenito-Moyet');
INSERT INTO Authors (author_name) VALUES ('Enrique Blanco');
INSERT INTO Authors (author_name) VALUES ('Ramon Folch');
INSERT INTO Authors (author_name) VALUES ('John B. Thompson');
INSERT INTO Authors (author_name) VALUES ('Émile Durkheim');
INSERT INTO Authors (author_name) VALUES ('Baltasar Gracián');
INSERT INTO Authors (author_name) VALUES ('La Boétie');
INSERT INTO Authors (author_name) VALUES ('Eduardo Galeano');
INSERT INTO Authors (author_name) VALUES ('Peter L. Berger');
INSERT INTO Authors (author_name) VALUES ('Joan Estruch');
INSERT INTO Authors (author_name) VALUES ('Salvador Cardús i Ros');
INSERT INTO Authors (author_name) VALUES ('David Young');
INSERT INTO Authors (author_name) VALUES ('Alexis de Tocqueville');
INSERT INTO Authors (author_name) VALUES ('Max Weber');
INSERT INTO Authors (author_name) VALUES ('Herodoto');
INSERT INTO Authors (author_name) VALUES ('Lucrecio');
INSERT INTO Authors (author_name) VALUES ('Alberto Bernabé Pajares');
INSERT INTO Authors (author_name) VALUES ('Isaiah Berlin');
INSERT INTO Authors (author_name) VALUES ('Demóstenes');
INSERT INTO Authors (author_name) VALUES ('Pascal Carré');
INSERT INTO Authors (author_name) VALUES ('Eduardo Infante');
INSERT INTO Authors (author_name) VALUES ('Yuval Noah Harari');
INSERT INTO Authors (author_name) VALUES ('Seneca');
INSERT INTO Authors (author_name) VALUES ('Niccolò Machiavelli');
INSERT INTO Authors (author_name) VALUES ('');
INSERT INTO Authors (author_name) VALUES ('René Descartes');
INSERT INTO Authors (author_name) VALUES ('Bertrand Russell');
INSERT INTO Authors (author_name) VALUES ('Viktor E. Frankl');
INSERT INTO Authors (author_name) VALUES ('Ana Frank');
INSERT INTO Authors (author_name) VALUES ('Baruch Spinoza');
INSERT INTO Authors (author_name) VALUES ('Fina Birulés Bertrán');
INSERT INTO Authors (author_name) VALUES ('Boethius');
INSERT INTO Authors (author_name) VALUES ('Platón');
INSERT INTO Authors (author_name) VALUES ('Marcus Aurelius');
INSERT INTO Authors (author_name) VALUES ('Massimo Pigliucci');
INSERT INTO Authors (author_name) VALUES ('Gregory Lopez');
INSERT INTO Authors (author_name) VALUES ('Gaius Julius Caesar');
INSERT INTO Authors (author_name) VALUES ('Antonio Machado');
INSERT INTO Authors (author_name) VALUES ('Marcus Tullius Cicero');
INSERT INTO Authors (author_name) VALUES ('Carlos García Gual');
INSERT INTO Authors (author_name) VALUES ('Epictetus');
INSERT INTO Authors (author_name) VALUES ('Aristotle');
INSERT INTO Authors (author_name) VALUES ('Aristóteles');
INSERT INTO Authors (author_name) VALUES ('Plutarco');
INSERT INTO Authors (author_name) VALUES ('Titus Livi');
INSERT INTO Authors (author_name) VALUES ('Mahatma Gandhi');
INSERT INTO Authors (author_name) VALUES ('Martin Luther King Jr.');
INSERT INTO Authors (author_name) VALUES ('Clayborne Carson');
INSERT INTO Authors (author_name) VALUES ('Sophocles');
INSERT INTO Authors (author_name) VALUES ('Homero');
INSERT INTO Authors (author_name) VALUES ('Homer');
INSERT INTO Authors (author_name) VALUES ('Anonymous');
INSERT INTO Authors (author_name) VALUES ('Frank Morison');
INSERT INTO Authors (author_name) VALUES ('Aurélien Géron');
INSERT INTO Authors (author_name) VALUES ('John Grisham');
INSERT INTO Authors (author_name) VALUES ('Kim Scott');
INSERT INTO Authors (author_name) VALUES ('Eduardo Punset');
INSERT INTO Authors (author_name) VALUES ('Nelson Mandela');
INSERT INTO Authors (author_name) VALUES ('Mark Manson');
INSERT INTO Authors (author_name) VALUES ('Nietzsche');
INSERT INTO Authors (author_name) VALUES ('Friederich Nietzsche');
INSERT INTO Authors (author_name) VALUES ('David Alegre Lorenz');
INSERT INTO Authors (author_name) VALUES ('Georges Simenon');
INSERT INTO Authors (author_name) VALUES ('Thomas Mann');
INSERT INTO Authors (author_name) VALUES ('Cesare Pavese');
INSERT INTO Authors (author_name) VALUES ('Ernest Hemingway');
INSERT INTO Authors (author_name) VALUES ('Alicia Rueda');
INSERT INTO Authors (author_name) VALUES ('Xosé Neira Vilas');
INSERT INTO Authors (author_name) VALUES ('George Orwell');
INSERT INTO Authors (author_name) VALUES ('Julio Cortázar');
INSERT INTO Authors (author_name) VALUES ('Álvaro Mutis');
INSERT INTO Authors (author_name) VALUES ('Gabriel García Márquez');
INSERT INTO Authors (author_name) VALUES ('José Saramago');
INSERT INTO Authors (author_name) VALUES ('Anton Chéjov');
INSERT INTO Authors (author_name) VALUES ('Fiódor Dostoievski');
INSERT INTO Authors (author_name) VALUES ('Máximo Gorki');
INSERT INTO Authors (author_name) VALUES ('Pushkin');
INSERT INTO Authors (author_name) VALUES ('Goethe');
INSERT INTO Authors (author_name) VALUES ('Albert Camus');
INSERT INTO Authors (author_name) VALUES ('William Golding');
INSERT INTO Authors (author_name) VALUES ('Flaubert');
INSERT INTO Authors (author_name) VALUES ('André Malraux');
INSERT INTO Authors (author_name) VALUES ('James Joyce');
INSERT INTO Authors (author_name) VALUES ('Joseph Conrad');
INSERT INTO Authors (author_name) VALUES ('Thomas Brussig');
INSERT INTO Authors (author_name) VALUES ('Vladimir Nabokov');
INSERT INTO Authors (author_name) VALUES ('H. G. Wells');
INSERT INTO Authors (author_name) VALUES ('Aldous Huxley');
INSERT INTO Authors (author_name) VALUES ('Isaac Asimov');
INSERT INTO Authors (author_name) VALUES ('Dmitri Shostakovich');
INSERT INTO Authors (author_name) VALUES ('Ryszard Kapuscinski');
INSERT INTO Authors (author_name) VALUES ('Raymond Carr');
INSERT INTO Authors (author_name) VALUES ('Luis F. Vila');
INSERT INTO Authors (author_name) VALUES ('Mayakovski');
INSERT INTO Authors (author_name) VALUES ('Konstantino Kavafis');
INSERT INTO Authors (author_name) VALUES ('Henrik Ibsen');
INSERT INTO Authors (author_name) VALUES ('William Shakespeare');
INSERT INTO Authors (author_name) VALUES ('Miguel Hernández');
INSERT INTO Authors (author_name) VALUES ('Walt Whitman');
INSERT INTO Authors (author_name) VALUES ('Mercè Saumell');
INSERT INTO Authors (author_name) VALUES ('Stephen Hawking');
INSERT INTO Authors (author_name) VALUES ('Joan Baptista Xuriguera');
INSERT INTO Authors (author_name) VALUES ('Charles Baudelaire');
INSERT INTO Authors (author_name) VALUES ('Arthur Rimbaud');
INSERT INTO Authors (author_name) VALUES ('Mario Benedetti');
INSERT INTO Authors (author_name) VALUES ('Vladimir Mayakovski');
INSERT INTO Authors (author_name) VALUES ('Sigmund Freud');
INSERT INTO Authors (author_name) VALUES ('Antonio Escohotado');
INSERT INTO Authors (author_name) VALUES ('Eugenio Trías');
INSERT INTO Authors (author_name) VALUES ('Manuel Rivas');
INSERT INTO Authors (author_name) VALUES ('Miquel Martí i Pol');
INSERT INTO Authors (author_name) VALUES ('José de Espronceda');
INSERT INTO Authors (author_name) VALUES ('Carmen Bernard; Serge Gruzinski');
INSERT INTO Authors (author_name) VALUES ('Didier Fassin');
INSERT INTO Authors (author_name) VALUES ('Arturo Pérez-Reverte');
INSERT INTO Authors (author_name) VALUES ('Perejaume');
INSERT INTO Authors (author_name) VALUES ('Martha C. Nussbaum');
INSERT INTO Authors (author_name) VALUES ('Friederich Hölderlin');
INSERT INTO Authors (author_name) VALUES ('Javier Marías');
INSERT INTO Authors (author_name) VALUES ('Almudena Sasiain');
INSERT INTO Authors (author_name) VALUES ('Jesús Adrián Escudero');
INSERT INTO Authors (author_name) VALUES ('Martin Heidegger');
INSERT INTO Authors (author_name) VALUES ('Michel Foucault');
INSERT INTO Authors (author_name) VALUES ('Soren Kierkeegard');
INSERT INTO Authors (author_name) VALUES ('Soren Kierkegaard');
INSERT INTO Authors (author_name) VALUES ('Byung-Chul Han');
INSERT INTO Authors (author_name) VALUES ('Daniel Gamper');
INSERT INTO Authors (author_name) VALUES ('Michel de Montaigne');
INSERT INTO Authors (author_name) VALUES ('Fernando Bárcena');
INSERT INTO Authors (author_name) VALUES ('Ortega y Gasset');
INSERT INTO Authors (author_name) VALUES ('Primo Levi');
INSERT INTO Authors (author_name) VALUES ('Rainer Maria Rilke');
INSERT INTO Authors (author_name) VALUES ('Arturo Barea');
INSERT INTO Authors (author_name) VALUES ('Juan Rulfo');
INSERT INTO Authors (author_name) VALUES ('Dante Aligheri');
INSERT INTO Authors (author_name) VALUES ('Theodor Adorno');
INSERT INTO Authors (author_name) VALUES ('W.J. Leatherbarrow');
INSERT INTO Authors (author_name) VALUES ('Paloma Ledrado Villafuertes');
INSERT INTO Authors (author_name) VALUES ('Eladio Romero García; Iván Romero Catalán');
INSERT INTO Authors (author_name) VALUES ('Erich From');
INSERT INTO Authors (author_name) VALUES ('Marcel Proust');
INSERT INTO Authors (author_name) VALUES ('F.M. Dostoyevski');
INSERT INTO Authors (author_name) VALUES ('José Martínez Millán');
INSERT INTO Authors (author_name) VALUES ('Georges Vigarello');
INSERT INTO Authors (author_name) VALUES ('Max F. Perutz');
INSERT INTO Authors (author_name) VALUES ('Shaila Romero Ferrer');
INSERT INTO Authors (author_name) VALUES ('Anna Funder');
INSERT INTO Authors (author_name) VALUES ('Philippe Claudel');
INSERT INTO Authors (author_name) VALUES ('Hegel');
INSERT INTO Authors (author_name) VALUES ('Dan Simmons');
INSERT INTO Authors (author_name) VALUES ('Ludmila Ulitskaya');
INSERT INTO Authors (author_name) VALUES ('Mao Zedong');
INSERT INTO Authors (author_name) VALUES ('Peter Thomson; Glendyr Sacks');
INSERT INTO Authors (author_name) VALUES ('Maceiras Fafián (editor)');
INSERT INTO Authors (author_name) VALUES ('Konrad Banachewicz; Luca Massaron');
INSERT INTO Authors (author_name) VALUES ('Fred Moseley; Tony Smith');
INSERT INTO Authors (author_name) VALUES ('Jesús Mosterín');
INSERT INTO Authors (author_name) VALUES ('William Outhwaite');
INSERT INTO Authors (author_name) VALUES ('Allen W. Wood');
INSERT INTO Authors (author_name) VALUES ('Nils Baer');
INSERT INTO Authors (author_name) VALUES ('Georg Von Lengerke; Dorte Schromges');
INSERT INTO Authors (author_name) VALUES ('Antonio Padial Soler');
INSERT INTO Authors (author_name) VALUES ('James Clear');
INSERT INTO Authors (author_name) VALUES ('Fyodor Dostoyevsky');
INSERT INTO Authors (author_name) VALUES ('Milton & Rose Fiedman');
INSERT INTO Authors (author_name) VALUES ('Adin Steinsaltz');
INSERT INTO Authors (author_name) VALUES ('Guías Azules');
INSERT INTO Authors (author_name) VALUES ('Fernando Sánchez Dragó');
INSERT INTO Authors (author_name) VALUES ('Benito Pérez Galdós');
INSERT INTO Authors (author_name) VALUES ('Glen Arnold');
INSERT INTO Authors (author_name) VALUES ('Natsume Soseki');
INSERT INTO Authors (author_name) VALUES ('Margaret Miers');
INSERT INTO Authors (author_name) VALUES ('Paul Godin');
INSERT INTO Authors (author_name) VALUES ('Geoff Wilkinson; Margaret Miers');
INSERT INTO Authors (author_name) VALUES ('Peter Morrall');
INSERT INTO Authors (author_name) VALUES ('Elizabeth Clark');
INSERT INTO Authors (author_name) VALUES ('Reyes Mate');