INSERT INTO Authors (author_id, author_name) VALUES (1, 'Brené Brown');
INSERT INTO Authors (author_id, author_name) VALUES (2, 'Ryan Holliday');
INSERT INTO Authors (author_id, author_name) VALUES (3, 'Harvard Business Review');
INSERT INTO Authors (author_id, author_name) VALUES (4, 'Lars Schmidt');
INSERT INTO Authors (author_id, author_name) VALUES (5, 'Robert Greene');
INSERT INTO Authors (author_id, author_name) VALUES (6, 'Lawrence Freedman');
INSERT INTO Authors (author_id, author_name) VALUES (7, 'Michael Bungay Stanier');
INSERT INTO Authors (author_id, author_name) VALUES (8, 'Julie Zhuo');
INSERT INTO Authors (author_id, author_name) VALUES (9, 'Josh Kaufman');
INSERT INTO Authors (author_id, author_name) VALUES (10, 'Jorge Riechman');
INSERT INTO Authors (author_id, author_name) VALUES (11, 'Erich Fromm');
INSERT INTO Authors (author_id, author_name) VALUES (12, 'Daniel Goleman');
INSERT INTO Authors (author_id, author_name) VALUES (13, 'Joe Navarro');
INSERT INTO Authors (author_id, author_name) VALUES (14, 'Jeff Weiss');
INSERT INTO Authors (author_id, author_name) VALUES (15, 'Amy Gallo');
INSERT INTO Authors (author_id, author_name) VALUES (16, 'Karen Dillon');
INSERT INTO Authors (author_id, author_name) VALUES (17, 'Max Tegmark');
INSERT INTO Authors (author_id, author_name) VALUES (18, 'Caterina Kostoula');
INSERT INTO Authors (author_id, author_name) VALUES (19, 'Chris Voss');
INSERT INTO Authors (author_id, author_name) VALUES (20, 'Robert B. Cialdini');
INSERT INTO Authors (author_id, author_name) VALUES (21, 'Dale Carnegie');
INSERT INTO Authors (author_id, author_name) VALUES (22, 'Noah J. Goldstein');
INSERT INTO Authors (author_id, author_name) VALUES (23, 'Steve J. Martin');
INSERT INTO Authors (author_id, author_name) VALUES (24, 'Igor Ryzov');
INSERT INTO Authors (author_id, author_name) VALUES (25, 'Vicenzo Venezia');
INSERT INTO Authors (author_id, author_name) VALUES (26, 'Jessica Pryce-Jones');
INSERT INTO Authors (author_id, author_name) VALUES (27, 'Rober Greene');
INSERT INTO Authors (author_id, author_name) VALUES (28, 'Henry Kissinger');
INSERT INTO Authors (author_id, author_name) VALUES (29, 'Simon Sinek');
INSERT INTO Authors (author_id, author_name) VALUES (30, 'Daniil Maslyuk');
INSERT INTO Authors (author_id, author_name) VALUES (31, 'Frank H. Netter');
INSERT INTO Authors (author_id, author_name) VALUES (32, 'Edward C. Weber DO');
INSERT INTO Authors (author_id, author_name) VALUES (33, 'Richard A. Jaffe');
INSERT INTO Authors (author_id, author_name) VALUES (34, 'José Luis Velayos');
INSERT INTO Authors (author_id, author_name) VALUES (35, 'G. Samama');
INSERT INTO Authors (author_id, author_name) VALUES (36, 'Shirley M. Tighe');
INSERT INTO Authors (author_id, author_name) VALUES (37, 'J.A.;GAL LOZANO');
INSERT INTO Authors (author_id, author_name) VALUES (38, 'John Connell (Editor)');
INSERT INTO Authors (author_id, author_name) VALUES (39, 'PIÉDROLA GIL');
INSERT INTO Authors (author_id, author_name) VALUES (40, 'Jane C. Rothrock');
INSERT INTO Authors (author_id, author_name) VALUES (41, 'Concepción Plaza Escribano');
INSERT INTO Authors (author_id, author_name) VALUES (42, 'Francisco Javier Medina Domínguez');
INSERT INTO Authors (author_id, author_name) VALUES (43, 'Jesús Hernández Gómez');
INSERT INTO Authors (author_id, author_name) VALUES (44, 'Jesús Martínez Casillas');
INSERT INTO Authors (author_id, author_name) VALUES (45, 'Juan José Martínez-Aedo Ollero');
INSERT INTO Authors (author_id, author_name) VALUES (46, 'Pilar Castro Ortiz');
INSERT INTO Authors (author_id, author_name) VALUES (47, 'Carol Mattson Porth');
INSERT INTO Authors (author_id, author_name) VALUES (48, 'Marie Bretonnier');
INSERT INTO Authors (author_id, author_name) VALUES (49, 'Emmanuel Godard');
INSERT INTO Authors (author_id, author_name) VALUES (50, 'Philippe Liria');
INSERT INTO Authors (author_id, author_name) VALUES (51, 'Jean Paul Sigé');
INSERT INTO Authors (author_id, author_name) VALUES (52, 'Marion Mistichelli');
INSERT INTO Authors (author_id, author_name) VALUES (53, 'Hermann Funk');
INSERT INTO Authors (author_id, author_name) VALUES (54, 'Christina Kuhn');
INSERT INTO Authors (author_id, author_name) VALUES (55, 'Silke Demme');
INSERT INTO Authors (author_id, author_name) VALUES (56, 'Sabino Zubiaurre Cortés');
INSERT INTO Authors (author_id, author_name) VALUES (57, 'Jesús María Arsuaga Ferreras');
INSERT INTO Authors (author_id, author_name) VALUES (58, 'Benito Garzón Sánchez');
INSERT INTO Authors (author_id, author_name) VALUES (59, 'Joanna Kotcher Fuller');
INSERT INTO Authors (author_id, author_name) VALUES (60, 'ROBERT FRANK');
INSERT INTO Authors (author_id, author_name) VALUES (61, 'BEN BERNANKE');
INSERT INTO Authors (author_id, author_name) VALUES (62, 'Antonio Pardo Merino');
INSERT INTO Authors (author_id, author_name) VALUES (63, 'Miguel Ángel Ruiz Díaz');
INSERT INTO Authors (author_id, author_name) VALUES (64, 'Anthea Hatfield');
INSERT INTO Authors (author_id, author_name) VALUES (65, 'Michael Tronson');
INSERT INTO Authors (author_id, author_name) VALUES (66, 'J. Liébana Ureña');
INSERT INTO Authors (author_id, author_name) VALUES (67, 'Joseph Hair');
INSERT INTO Authors (author_id, author_name) VALUES (68, 'Ronald L. Tatham');
INSERT INTO Authors (author_id, author_name) VALUES (69, 'Sarah Nettleton');
INSERT INTO Authors (author_id, author_name) VALUES (70, 'Sabine Hossenfelder');
INSERT INTO Authors (author_id, author_name) VALUES (71, 'Margaret J. Fehrenbach Charles A. Babbush');
INSERT INTO Authors (author_id, author_name) VALUES (72, 'Dan L. Longo (editor)');
INSERT INTO Authors (author_id, author_name) VALUES (73, 'M.D. Fauci');
INSERT INTO Authors (author_id, author_name) VALUES (74, 'Anthony S. (Editor)');
INSERT INTO Authors (author_id, author_name) VALUES (75, 'M.D. Kasper');
INSERT INTO Authors (author_id, author_name) VALUES (76, 'Dennis L. (Editor)');
INSERT INTO Authors (author_id, author_name) VALUES (77, 'M.d. Hauser');
INSERT INTO Authors (author_id, author_name) VALUES (78, 'Stephen L. (Editor)');
INSERT INTO Authors (author_id, author_name) VALUES (79, 'Ph.D. Jameson');
INSERT INTO Authors (author_id, author_name) VALUES (80, 'J. Larry');
INSERT INTO Authors (author_id, author_name) VALUES (81, 'M.D. (Editor)');
INSERT INTO Authors (author_id, author_name) VALUES (82, 'Jeremy Harvey');
INSERT INTO Authors (author_id, author_name) VALUES (83, 'Raymond Quivy');
INSERT INTO Authors (author_id, author_name) VALUES (84, 'David Quammen');
INSERT INTO Authors (author_id, author_name) VALUES (85, 'Lisa Randall');
INSERT INTO Authors (author_id, author_name) VALUES (86, 'Alan Stern');
INSERT INTO Authors (author_id, author_name) VALUES (87, 'David Grinspoon');
INSERT INTO Authors (author_id, author_name) VALUES (88, 'Anthony Giddens');
INSERT INTO Authors (author_id, author_name) VALUES (89, 'Karen Birdsall');
INSERT INTO Authors (author_id, author_name) VALUES (90, 'J. de Echano');
INSERT INTO Authors (author_id, author_name) VALUES (91, 'E. Martínez');
INSERT INTO Authors (author_id, author_name) VALUES (92, 'P. Montarelo');
INSERT INTO Authors (author_id, author_name) VALUES (93, 'L. Navlet');
INSERT INTO Authors (author_id, author_name) VALUES (94, 'Pierre Bourdieu');
INSERT INTO Authors (author_id, author_name) VALUES (95, 'Jean-Claude Passeron');
INSERT INTO Authors (author_id, author_name) VALUES (96, 'Enrique Blanco García');
INSERT INTO Authors (author_id, author_name) VALUES (97, 'Harold R. Kerbo');
INSERT INTO Authors (author_id, author_name) VALUES (98, 'Julio Aróstegui Sánchez');
INSERT INTO Authors (author_id, author_name) VALUES (99, 'Josep Maria Esquirol');
INSERT INTO Authors (author_id, author_name) VALUES (100, 'Bernal Díaz del Castillo');
INSERT INTO Authors (author_id, author_name) VALUES (101, 'Edward Gibbon');
INSERT INTO Authors (author_id, author_name) VALUES (102, 'Alexis Jenni');
INSERT INTO Authors (author_id, author_name) VALUES (103, 'Erving Goffman');
INSERT INTO Authors (author_id, author_name) VALUES (104, 'Josep Alsinet');
INSERT INTO Authors (author_id, author_name) VALUES (105, 'Clara Riba');
INSERT INTO Authors (author_id, author_name) VALUES (106, 'Montserrat Ribera');
INSERT INTO Authors (author_id, author_name) VALUES (107, 'Joan Subirats');
INSERT INTO Authors (author_id, author_name) VALUES (108, 'Ignacio Sánchez-Cuenca');
INSERT INTO Authors (author_id, author_name) VALUES (109, 'Thorstein Veblen');
INSERT INTO Authors (author_id, author_name) VALUES (110, 'Martha Banta');
INSERT INTO Authors (author_id, author_name) VALUES (111, 'Ralf Dahrendorf');
INSERT INTO Authors (author_id, author_name) VALUES (112, 'Umberto Eco');
INSERT INTO Authors (author_id, author_name) VALUES (113, 'Salvador Giner');
INSERT INTO Authors (author_id, author_name) VALUES (114, 'Kottak');
INSERT INTO Authors (author_id, author_name) VALUES (115, 'Diego Fusaro');
INSERT INTO Authors (author_id, author_name) VALUES (116, 'Manuel Pérez Yruela');
INSERT INTO Authors (author_id, author_name) VALUES (117, 'Jean-Yves Calvez');
INSERT INTO Authors (author_id, author_name) VALUES (118, 'Anwar Shaikh');
INSERT INTO Authors (author_id, author_name) VALUES (119, 'JANE I SANAHUJAM ANGELA ; GUITERAS');
INSERT INTO Authors (author_id, author_name) VALUES (120, 'Various');
INSERT INTO Authors (author_id, author_name) VALUES (121, 'Laura Tam');
INSERT INTO Authors (author_id, author_name) VALUES (122, 'Josep Torras i Rodergas');
INSERT INTO Authors (author_id, author_name) VALUES (123, 'Paulina Christensen');
INSERT INTO Authors (author_id, author_name) VALUES (124, 'Anne Fox');
INSERT INTO Authors (author_id, author_name) VALUES (125, 'Fyodor Dostoevsky');
INSERT INTO Authors (author_id, author_name) VALUES (126, 'P.D. James');
INSERT INTO Authors (author_id, author_name) VALUES (127, 'Silvia Castells Molina');
INSERT INTO Authors (author_id, author_name) VALUES (128, 'Max Horkheimer');
INSERT INTO Authors (author_id, author_name) VALUES (129, 'Theodor W. Adorno');
INSERT INTO Authors (author_id, author_name) VALUES (130, 'Antonio Gramsci');
INSERT INTO Authors (author_id, author_name) VALUES (131, 'Walter Benjamin');
INSERT INTO Authors (author_id, author_name) VALUES (132, 'Daniel H. Pink');
INSERT INTO Authors (author_id, author_name) VALUES (133, 'Jean-Paul Sartre');
INSERT INTO Authors (author_id, author_name) VALUES (134, 'György Lukács');
INSERT INTO Authors (author_id, author_name) VALUES (135, 'Thomas Piketty');
INSERT INTO Authors (author_id, author_name) VALUES (136, 'Paul Lafargue');
INSERT INTO Authors (author_id, author_name) VALUES (137, 'Ernesto Laclau');
INSERT INTO Authors (author_id, author_name) VALUES (138, 'Chantal Mouffe');
INSERT INTO Authors (author_id, author_name) VALUES (139, 'O.G. Sanchis');
INSERT INTO Authors (author_id, author_name) VALUES (140, 'Joan E. Garcés');
INSERT INTO Authors (author_id, author_name) VALUES (141, 'Louis Althusser');
INSERT INTO Authors (author_id, author_name) VALUES (142, 'Vladimir Lenin');
INSERT INTO Authors (author_id, author_name) VALUES (143, 'Rosa Luxemburg');
INSERT INTO Authors (author_id, author_name) VALUES (144, 'Francisco Fernández Buey');
INSERT INTO Authors (author_id, author_name) VALUES (145, 'Rubén Vega García');
INSERT INTO Authors (author_id, author_name) VALUES (146, 'Donald Sassoon');
INSERT INTO Authors (author_id, author_name) VALUES (147, 'G.A. Cohen');
INSERT INTO Authors (author_id, author_name) VALUES (148, 'Daniel Kahneman');
INSERT INTO Authors (author_id, author_name) VALUES (149, 'Jennifer Geary');
INSERT INTO Authors (author_id, author_name) VALUES (150, 'Mario Amorós');
INSERT INTO Authors (author_id, author_name) VALUES (151, 'Robert Service');
INSERT INTO Authors (author_id, author_name) VALUES (152, 'José Luis Martín');
INSERT INTO Authors (author_id, author_name) VALUES (153, 'David McLellan');
INSERT INTO Authors (author_id, author_name) VALUES (154, 'Gustavo Vidal Manzanares');
INSERT INTO Authors (author_id, author_name) VALUES (155, 'Georg Wilhelm Friedrich Hegel');
INSERT INTO Authors (author_id, author_name) VALUES (156, 'Karl Marx');
INSERT INTO Authors (author_id, author_name) VALUES (157, 'Andrés Saborit');
INSERT INTO Authors (author_id, author_name) VALUES (158, 'Manuel Tuñón de Lara');
INSERT INTO Authors (author_id, author_name) VALUES (159, 'Luis Sala González');
INSERT INTO Authors (author_id, author_name) VALUES (160, 'Juan Pablo Fusi');
INSERT INTO Authors (author_id, author_name) VALUES (161, 'Carme Cebrián');
INSERT INTO Authors (author_id, author_name) VALUES (162, 'Jose del Barrio');
INSERT INTO Authors (author_id, author_name) VALUES (163, 'John Rentoul');
INSERT INTO Authors (author_id, author_name) VALUES (164, 'Isidre Molas');
INSERT INTO Authors (author_id, author_name) VALUES (165, 'Manuel Alcántara; Antonia Martínez');
INSERT INTO Authors (author_id, author_name) VALUES (166, 'Gabriel Jackson');
INSERT INTO Authors (author_id, author_name) VALUES (167, 'Larousse');
INSERT INTO Authors (author_id, author_name) VALUES (168, 'Paul Coggle');
INSERT INTO Authors (author_id, author_name) VALUES (169, 'Heiner Schenke');
INSERT INTO Authors (author_id, author_name) VALUES (170, 'Lydia Vellaccio');
INSERT INTO Authors (author_id, author_name) VALUES (171, 'Bescherelle');
INSERT INTO Authors (author_id, author_name) VALUES (172, 'Núria Benedito Pujol');
INSERT INTO Authors (author_id, author_name) VALUES (173, 'Sebastián Trujillo Muñoz');
INSERT INTO Authors (author_id, author_name) VALUES (174, 'Didier Fassin (Editor)');
INSERT INTO Authors (author_id, author_name) VALUES (175, 'Dominique Memmi (Editor)');
INSERT INTO Authors (author_id, author_name) VALUES (176, 'Xavier Bonal');
INSERT INTO Authors (author_id, author_name) VALUES (177, 'Carlota Sole');
INSERT INTO Authors (author_id, author_name) VALUES (178, 'Enrique Santamaria Lorenzo');
INSERT INTO Authors (author_id, author_name) VALUES (179, 'Olga Solas Gaspar');
INSERT INTO Authors (author_id, author_name) VALUES (180, 'Norbert Elias');
INSERT INTO Authors (author_id, author_name) VALUES (181, 'Sònia Parella Rubio');
INSERT INTO Authors (author_id, author_name) VALUES (182, 'Manuel Moreno Preciado');
INSERT INTO Authors (author_id, author_name) VALUES (183, 'Susan Cain');
INSERT INTO Authors (author_id, author_name) VALUES (184, 'Slavoj Zizek');
INSERT INTO Authors (author_id, author_name) VALUES (185, 'Thomas Erikson');
INSERT INTO Authors (author_id, author_name) VALUES (186, 'Richard Sennett');
INSERT INTO Authors (author_id, author_name) VALUES (187, 'Hannah Arendt');
INSERT INTO Authors (author_id, author_name) VALUES (188, 'Raúl Aguilar Cestero');
INSERT INTO Authors (author_id, author_name) VALUES (189, 'Lynda Juall Carpenito-Moyet');
INSERT INTO Authors (author_id, author_name) VALUES (190, 'Enrique Blanco');
INSERT INTO Authors (author_id, author_name) VALUES (191, 'Ramon Folch');
INSERT INTO Authors (author_id, author_name) VALUES (192, 'John B. Thompson');
INSERT INTO Authors (author_id, author_name) VALUES (193, 'Émile Durkheim');
INSERT INTO Authors (author_id, author_name) VALUES (194, 'Baltasar Gracián');
INSERT INTO Authors (author_id, author_name) VALUES (195, 'La Boétie');
INSERT INTO Authors (author_id, author_name) VALUES (196, 'Eduardo Galeano');
INSERT INTO Authors (author_id, author_name) VALUES (197, 'Peter L. Berger');
INSERT INTO Authors (author_id, author_name) VALUES (198, 'Joan Estruch');
INSERT INTO Authors (author_id, author_name) VALUES (199, 'Salvador Cardús i Ros');
INSERT INTO Authors (author_id, author_name) VALUES (200, 'David Young');
INSERT INTO Authors (author_id, author_name) VALUES (201, 'Alexis de Tocqueville');
INSERT INTO Authors (author_id, author_name) VALUES (202, 'Max Weber');
INSERT INTO Authors (author_id, author_name) VALUES (203, 'Herodoto');
INSERT INTO Authors (author_id, author_name) VALUES (204, 'Lucrecio');
INSERT INTO Authors (author_id, author_name) VALUES (205, 'Alberto Bernabé Pajares');
INSERT INTO Authors (author_id, author_name) VALUES (206, 'Isaiah Berlin');
INSERT INTO Authors (author_id, author_name) VALUES (207, 'Demóstenes');
INSERT INTO Authors (author_id, author_name) VALUES (208, 'Pascal Carré');
INSERT INTO Authors (author_id, author_name) VALUES (209, 'Eduardo Infante');
INSERT INTO Authors (author_id, author_name) VALUES (210, 'Yuval Noah Harari');
INSERT INTO Authors (author_id, author_name) VALUES (211, 'Seneca');
INSERT INTO Authors (author_id, author_name) VALUES (212, 'Niccolò Machiavelli');
INSERT INTO Authors (author_id, author_name) VALUES (213, '');
INSERT INTO Authors (author_id, author_name) VALUES (214, 'René Descartes');
INSERT INTO Authors (author_id, author_name) VALUES (215, 'Bertrand Russell');
INSERT INTO Authors (author_id, author_name) VALUES (216, 'Viktor E. Frankl');
INSERT INTO Authors (author_id, author_name) VALUES (217, 'Ana Frank');
INSERT INTO Authors (author_id, author_name) VALUES (218, 'Baruch Spinoza');
INSERT INTO Authors (author_id, author_name) VALUES (219, 'Fina Birulés Bertrán');
INSERT INTO Authors (author_id, author_name) VALUES (220, 'Boethius');
INSERT INTO Authors (author_id, author_name) VALUES (221, 'Platón');
INSERT INTO Authors (author_id, author_name) VALUES (222, 'Marcus Aurelius');
INSERT INTO Authors (author_id, author_name) VALUES (223, 'Massimo Pigliucci');
INSERT INTO Authors (author_id, author_name) VALUES (224, 'Gregory Lopez');
INSERT INTO Authors (author_id, author_name) VALUES (225, 'Gaius Julius Caesar');
INSERT INTO Authors (author_id, author_name) VALUES (226, 'Antonio Machado');
INSERT INTO Authors (author_id, author_name) VALUES (227, 'Marcus Tullius Cicero');
INSERT INTO Authors (author_id, author_name) VALUES (228, 'Carlos García Gual');
INSERT INTO Authors (author_id, author_name) VALUES (229, 'Epictetus');
INSERT INTO Authors (author_id, author_name) VALUES (230, 'Aristotle');
INSERT INTO Authors (author_id, author_name) VALUES (231, 'Aristóteles');
INSERT INTO Authors (author_id, author_name) VALUES (232, 'Plutarco');
INSERT INTO Authors (author_id, author_name) VALUES (233, 'Titus Livi');
INSERT INTO Authors (author_id, author_name) VALUES (234, 'Mahatma Gandhi');
INSERT INTO Authors (author_id, author_name) VALUES (235, 'Martin Luther King Jr.');
INSERT INTO Authors (author_id, author_name) VALUES (236, 'Clayborne Carson');
INSERT INTO Authors (author_id, author_name) VALUES (237, 'Sophocles');
INSERT INTO Authors (author_id, author_name) VALUES (238, 'Homero');
INSERT INTO Authors (author_id, author_name) VALUES (239, 'Homer');
INSERT INTO Authors (author_id, author_name) VALUES (240, 'Anonymous');
INSERT INTO Authors (author_id, author_name) VALUES (241, 'Frank Morison');
INSERT INTO Authors (author_id, author_name) VALUES (242, 'Aurélien Géron');
INSERT INTO Authors (author_id, author_name) VALUES (243, 'John Grisham');
INSERT INTO Authors (author_id, author_name) VALUES (244, 'Kim Scott');
INSERT INTO Authors (author_id, author_name) VALUES (245, 'Eduardo Punset');
INSERT INTO Authors (author_id, author_name) VALUES (246, 'Nelson Mandela');
INSERT INTO Authors (author_id, author_name) VALUES (247, 'Mark Manson');
INSERT INTO Authors (author_id, author_name) VALUES (248, 'Nietzsche');
INSERT INTO Authors (author_id, author_name) VALUES (249, 'Friederich Nietzsche');
INSERT INTO Authors (author_id, author_name) VALUES (250, 'David Alegre Lorenz');
INSERT INTO Authors (author_id, author_name) VALUES (251, 'Georges Simenon');
INSERT INTO Authors (author_id, author_name) VALUES (252, 'Thomas Mann');
INSERT INTO Authors (author_id, author_name) VALUES (253, 'Cesare Pavese');
INSERT INTO Authors (author_id, author_name) VALUES (254, 'Ernest Hemingway');
INSERT INTO Authors (author_id, author_name) VALUES (255, 'Alicia Rueda');
INSERT INTO Authors (author_id, author_name) VALUES (256, 'Xosé Neira Vilas');
INSERT INTO Authors (author_id, author_name) VALUES (257, 'George Orwell');
INSERT INTO Authors (author_id, author_name) VALUES (258, 'Julio Cortázar');
INSERT INTO Authors (author_id, author_name) VALUES (259, 'Álvaro Mutis');
INSERT INTO Authors (author_id, author_name) VALUES (260, 'Gabriel García Márquez');
INSERT INTO Authors (author_id, author_name) VALUES (261, 'José Saramago');
INSERT INTO Authors (author_id, author_name) VALUES (262, 'Anton Chéjov');
INSERT INTO Authors (author_id, author_name) VALUES (263, 'Fiódor Dostoievski');
INSERT INTO Authors (author_id, author_name) VALUES (264, 'Máximo Gorki');
INSERT INTO Authors (author_id, author_name) VALUES (265, 'Pushkin');
INSERT INTO Authors (author_id, author_name) VALUES (266, 'Goethe');
INSERT INTO Authors (author_id, author_name) VALUES (267, 'Albert Camus');
INSERT INTO Authors (author_id, author_name) VALUES (268, 'William Golding');
INSERT INTO Authors (author_id, author_name) VALUES (269, 'Flaubert');
INSERT INTO Authors (author_id, author_name) VALUES (270, 'André Malraux');
INSERT INTO Authors (author_id, author_name) VALUES (271, 'James Joyce');
INSERT INTO Authors (author_id, author_name) VALUES (272, 'Joseph Conrad');
INSERT INTO Authors (author_id, author_name) VALUES (273, 'Thomas Brussig');
INSERT INTO Authors (author_id, author_name) VALUES (274, 'Vladimir Nabokov');
INSERT INTO Authors (author_id, author_name) VALUES (275, 'H. G. Wells');
INSERT INTO Authors (author_id, author_name) VALUES (276, 'Aldous Huxley');
INSERT INTO Authors (author_id, author_name) VALUES (277, 'Isaac Asimov');
INSERT INTO Authors (author_id, author_name) VALUES (278, 'Dmitri Shostakovich');
INSERT INTO Authors (author_id, author_name) VALUES (279, 'Ryszard Kapuscinski');
INSERT INTO Authors (author_id, author_name) VALUES (280, 'Raymond Carr');
INSERT INTO Authors (author_id, author_name) VALUES (281, 'Luis F. Vila');
INSERT INTO Authors (author_id, author_name) VALUES (282, 'Mayakovski');
INSERT INTO Authors (author_id, author_name) VALUES (283, 'Konstantino Kavafis');
INSERT INTO Authors (author_id, author_name) VALUES (284, 'Henrik Ibsen');
INSERT INTO Authors (author_id, author_name) VALUES (285, 'William Shakespeare');
INSERT INTO Authors (author_id, author_name) VALUES (286, 'Miguel Hernández');
INSERT INTO Authors (author_id, author_name) VALUES (287, 'Walt Whitman');
INSERT INTO Authors (author_id, author_name) VALUES (288, 'Mercè Saumell');
INSERT INTO Authors (author_id, author_name) VALUES (289, 'Stephen Hawking');
INSERT INTO Authors (author_id, author_name) VALUES (290, 'Joan Baptista Xuriguera');
INSERT INTO Authors (author_id, author_name) VALUES (291, 'Charles Baudelaire');
INSERT INTO Authors (author_id, author_name) VALUES (292, 'Arthur Rimbaud');
INSERT INTO Authors (author_id, author_name) VALUES (293, 'Mario Benedetti');
INSERT INTO Authors (author_id, author_name) VALUES (294, 'Vladimir Mayakovski');
INSERT INTO Authors (author_id, author_name) VALUES (295, 'Sigmund Freud');
INSERT INTO Authors (author_id, author_name) VALUES (296, 'Antonio Escohotado');
INSERT INTO Authors (author_id, author_name) VALUES (297, 'Eugenio Trías');
INSERT INTO Authors (author_id, author_name) VALUES (298, 'Manuel Rivas');
INSERT INTO Authors (author_id, author_name) VALUES (299, 'Miquel Martí i Pol');
INSERT INTO Authors (author_id, author_name) VALUES (300, 'José de Espronceda');
INSERT INTO Authors (author_id, author_name) VALUES (301, 'Carmen Bernard; Serge Gruzinski');
INSERT INTO Authors (author_id, author_name) VALUES (302, 'Didier Fassin');
INSERT INTO Authors (author_id, author_name) VALUES (303, 'Arturo Pérez-Reverte');
INSERT INTO Authors (author_id, author_name) VALUES (304, 'Perejaume');
INSERT INTO Authors (author_id, author_name) VALUES (305, 'Martha C. Nussbaum');
INSERT INTO Authors (author_id, author_name) VALUES (306, 'Friederich Hölderlin');
INSERT INTO Authors (author_id, author_name) VALUES (307, 'Javier Marías');
INSERT INTO Authors (author_id, author_name) VALUES (308, 'Almudena Sasiain');
INSERT INTO Authors (author_id, author_name) VALUES (309, 'Jesús Adrián Escudero');
INSERT INTO Authors (author_id, author_name) VALUES (310, 'Martin Heidegger');
INSERT INTO Authors (author_id, author_name) VALUES (311, 'Michel Foucault');
INSERT INTO Authors (author_id, author_name) VALUES (312, 'Soren Kierkeegard');
INSERT INTO Authors (author_id, author_name) VALUES (313, 'Soren Kierkegaard');
INSERT INTO Authors (author_id, author_name) VALUES (314, 'Byung-Chul Han');
INSERT INTO Authors (author_id, author_name) VALUES (315, 'Daniel Gamper');
INSERT INTO Authors (author_id, author_name) VALUES (316, 'Michel de Montaigne');
INSERT INTO Authors (author_id, author_name) VALUES (317, 'Fernando Bárcena');
INSERT INTO Authors (author_id, author_name) VALUES (318, 'Ortega y Gasset');
INSERT INTO Authors (author_id, author_name) VALUES (319, 'Primo Levi');
INSERT INTO Authors (author_id, author_name) VALUES (320, 'Rainer Maria Rilke');
INSERT INTO Authors (author_id, author_name) VALUES (321, 'Arturo Barea');
INSERT INTO Authors (author_id, author_name) VALUES (322, 'Juan Rulfo');
INSERT INTO Authors (author_id, author_name) VALUES (323, 'Dante Aligheri');
INSERT INTO Authors (author_id, author_name) VALUES (324, 'Theodor Adorno');
INSERT INTO Authors (author_id, author_name) VALUES (325, 'W.J. Leatherbarrow');
INSERT INTO Authors (author_id, author_name) VALUES (326, 'Paloma Ledrado Villafuertes');
INSERT INTO Authors (author_id, author_name) VALUES (327, 'Eladio Romero García; Iván Romero Catalán');
INSERT INTO Authors (author_id, author_name) VALUES (328, 'Erich From');
INSERT INTO Authors (author_id, author_name) VALUES (329, 'Marcel Proust');
INSERT INTO Authors (author_id, author_name) VALUES (330, 'F.M. Dostoyevski');
INSERT INTO Authors (author_id, author_name) VALUES (331, 'José Martínez Millán');
INSERT INTO Authors (author_id, author_name) VALUES (332, 'Georges Vigarello');
INSERT INTO Authors (author_id, author_name) VALUES (333, 'Max F. Perutz');
INSERT INTO Authors (author_id, author_name) VALUES (334, 'Shaila Romero Ferrer');
INSERT INTO Authors (author_id, author_name) VALUES (335, 'Anna Funder');
INSERT INTO Authors (author_id, author_name) VALUES (336, 'Philippe Claudel');
INSERT INTO Authors (author_id, author_name) VALUES (337, 'Hegel');
INSERT INTO Authors (author_id, author_name) VALUES (338, 'Dan Simmons');
INSERT INTO Authors (author_id, author_name) VALUES (339, 'Ludmila Ulitskaya');
INSERT INTO Authors (author_id, author_name) VALUES (340, 'Mao Zedong');
INSERT INTO Authors (author_id, author_name) VALUES (341, 'Peter Thomson; Glendyr Sacks');
INSERT INTO Authors (author_id, author_name) VALUES (342, 'Maceiras Fafián (editor)');
INSERT INTO Authors (author_id, author_name) VALUES (343, 'Konrad Banachewicz; Luca Massaron');
INSERT INTO Authors (author_id, author_name) VALUES (344, 'Fred Moseley; Tony Smith');
INSERT INTO Authors (author_id, author_name) VALUES (345, 'Jesús Mosterín');
INSERT INTO Authors (author_id, author_name) VALUES (346, 'William Outhwaite');
INSERT INTO Authors (author_id, author_name) VALUES (347, 'Allen W. Wood');
INSERT INTO Authors (author_id, author_name) VALUES (348, 'Nils Baer');
INSERT INTO Authors (author_id, author_name) VALUES (349, 'Georg Von Lengerke; Dorte Schromges');
INSERT INTO Authors (author_id, author_name) VALUES (350, 'Antonio Padial Soler');
INSERT INTO Authors (author_id, author_name) VALUES (351, 'James Clear');
INSERT INTO Authors (author_id, author_name) VALUES (352, 'Fyodor Dostoyevsky');
INSERT INTO Authors (author_id, author_name) VALUES (353, 'Milton & Rose Fiedman');
INSERT INTO Authors (author_id, author_name) VALUES (354, 'Adin Steinsaltz');
INSERT INTO Authors (author_id, author_name) VALUES (355, 'Guías Azules');
INSERT INTO Authors (author_id, author_name) VALUES (356, 'Fernando Sánchez Dragó');
INSERT INTO Authors (author_id, author_name) VALUES (357, 'Benito Pérez Galdós');
INSERT INTO Authors (author_id, author_name) VALUES (358, 'Glen Arnold');
INSERT INTO Authors (author_id, author_name) VALUES (359, 'Natsume Soseki');
INSERT INTO Authors (author_id, author_name) VALUES (360, 'Margaret Miers');
INSERT INTO Authors (author_id, author_name) VALUES (361, 'Paul Godin');
INSERT INTO Authors (author_id, author_name) VALUES (362, 'Geoff Wilkinson; Margaret Miers');
INSERT INTO Authors (author_id, author_name) VALUES (363, 'Peter Morrall');
INSERT INTO Authors (author_id, author_name) VALUES (364, 'Elizabeth Clark');
INSERT INTO Authors (author_id, author_name) VALUES (365, 'Reyes Mate');