INSERT INTO Genres (genre_name) VALUES ('Nonfiction');
INSERT INTO Genres (genre_name) VALUES ('Leadership');
INSERT INTO Genres (genre_name) VALUES ('Business');
INSERT INTO Genres (genre_name) VALUES ('Self Help');
INSERT INTO Genres (genre_name) VALUES ('Personal Development');
INSERT INTO Genres (genre_name) VALUES ('Psychology');
INSERT INTO Genres (genre_name) VALUES ('Management');
INSERT INTO Genres (genre_name) VALUES ('Education');
INSERT INTO Genres (genre_name) VALUES ('Philosophy');
INSERT INTO Genres (genre_name) VALUES ('Productivity');
INSERT INTO Genres (genre_name) VALUES ('History');
INSERT INTO Genres (genre_name) VALUES ('Personnel management');
INSERT INTO Genres (genre_name) VALUES ('War');
INSERT INTO Genres (genre_name) VALUES ('Politics');
INSERT INTO Genres (genre_name) VALUES ('Military Fiction');
INSERT INTO Genres (genre_name) VALUES ('Military History');
INSERT INTO Genres (genre_name) VALUES ('Economics');
INSERT INTO Genres (genre_name) VALUES ('Communication');
INSERT INTO Genres (genre_name) VALUES ('Design');
INSERT INTO Genres (genre_name) VALUES ('Audiobook');
INSERT INTO Genres (genre_name) VALUES ('Entrepreneurship');
INSERT INTO Genres (genre_name) VALUES ('Finance');
INSERT INTO Genres (genre_name) VALUES ('social sciences');
INSERT INTO Genres (genre_name) VALUES ('ethics');
INSERT INTO Genres (genre_name) VALUES ('socio-ecological crises');
INSERT INTO Genres (genre_name) VALUES ('political philosophy');
INSERT INTO Genres (genre_name) VALUES ('Sociology');
INSERT INTO Genres (genre_name) VALUES ('German Literature');
INSERT INTO Genres (genre_name) VALUES ('Psychoanalysis');
INSERT INTO Genres (genre_name) VALUES ('Classics');
INSERT INTO Genres (genre_name) VALUES ('Science');
INSERT INTO Genres (genre_name) VALUES ('Relationships');
INSERT INTO Genres (genre_name) VALUES ('How To');
INSERT INTO Genres (genre_name) VALUES ('Reference');
INSERT INTO Genres (genre_name) VALUES ('Artificial Intelligence');
INSERT INTO Genres (genre_name) VALUES ('Technology');
INSERT INTO Genres (genre_name) VALUES ('Futurism');
INSERT INTO Genres (genre_name) VALUES ('Computer Science');
INSERT INTO Genres (genre_name) VALUES ('Physics');
INSERT INTO Genres (genre_name) VALUES ('Social');
INSERT INTO Genres (genre_name) VALUES ('International Relations');
INSERT INTO Genres (genre_name) VALUES ('Political Science');
INSERT INTO Genres (genre_name) VALUES ('World History');
INSERT INTO Genres (genre_name) VALUES ('American History');
INSERT INTO Genres (genre_name) VALUES ('Informatics');
INSERT INTO Genres (genre_name) VALUES ('Software');
INSERT INTO Genres (genre_name) VALUES ('Microsoft');
INSERT INTO Genres (genre_name) VALUES ('Medicine');
INSERT INTO Genres (genre_name) VALUES ('Medical');
INSERT INTO Genres (genre_name) VALUES ('Textbooks');
INSERT INTO Genres (genre_name) VALUES ('Health');
INSERT INTO Genres (genre_name) VALUES ('Biology');
INSERT INTO Genres (genre_name) VALUES ('School');
INSERT INTO Genres (genre_name) VALUES ('Anatomy');
INSERT INTO Genres (genre_name) VALUES ('Anaesthesia');
INSERT INTO Genres (genre_name) VALUES ('Odontology');
INSERT INTO Genres (genre_name) VALUES ('Nursing');
INSERT INTO Genres (genre_name) VALUES ('Operating room');
INSERT INTO Genres (genre_name) VALUES ('Biochemistry');
INSERT INTO Genres (genre_name) VALUES ('Migration studies');
INSERT INTO Genres (genre_name) VALUES ('Healthcare');
INSERT INTO Genres (genre_name) VALUES ('Preventive Medicine');
INSERT INTO Genres (genre_name) VALUES ('Perioperative Nursing');
INSERT INTO Genres (genre_name) VALUES ('Languages');
INSERT INTO Genres (genre_name) VALUES ('French');
INSERT INTO Genres (genre_name) VALUES ('German');
INSERT INTO Genres (genre_name) VALUES ('Chemistry');
INSERT INTO Genres (genre_name) VALUES ('Operating Room');
INSERT INTO Genres (genre_name) VALUES ('Economy');
INSERT INTO Genres (genre_name) VALUES ('Political Economy');
INSERT INTO Genres (genre_name) VALUES ('Statistics');
INSERT INTO Genres (genre_name) VALUES ('Oral Microbiology');
INSERT INTO Genres (genre_name) VALUES ('Dentistry');
INSERT INTO Genres (genre_name) VALUES ('Sociology of Health');
INSERT INTO Genres (genre_name) VALUES ('Mathematics');
INSERT INTO Genres (genre_name) VALUES ('Popular Science');
INSERT INTO Genres (genre_name) VALUES ('Internal Medicine');
INSERT INTO Genres (genre_name) VALUES ('Computational Chemistry');
INSERT INTO Genres (genre_name) VALUES ('Academic');
INSERT INTO Genres (genre_name) VALUES ('Social Science');
INSERT INTO Genres (genre_name) VALUES ('Evolution');
INSERT INTO Genres (genre_name) VALUES ('Nature');
INSERT INTO Genres (genre_name) VALUES ('Quantum Mechanics');
INSERT INTO Genres (genre_name) VALUES ('Astronomy');
INSERT INTO Genres (genre_name) VALUES ('Space');
INSERT INTO Genres (genre_name) VALUES ('Engineering');
INSERT INTO Genres (genre_name) VALUES ('Science Textbooks');
INSERT INTO Genres (genre_name) VALUES ('Academic School');
INSERT INTO Genres (genre_name) VALUES ('Society');
INSERT INTO Genres (genre_name) VALUES ('Cultural');
INSERT INTO Genres (genre_name) VALUES ('Genomics');
INSERT INTO Genres (genre_name) VALUES ('Socialism');
INSERT INTO Genres (genre_name) VALUES ('II República');
INSERT INTO Genres (genre_name) VALUES ('Spain');
INSERT INTO Genres (genre_name) VALUES ('Spanish Literature');
INSERT INTO Genres (genre_name) VALUES ('Historical Memoir');
INSERT INTO Genres (genre_name) VALUES ('Latin American');
INSERT INTO Genres (genre_name) VALUES ('Biography');
INSERT INTO Genres (genre_name) VALUES ('Roman Empire');
INSERT INTO Genres (genre_name) VALUES ('Fiction');
INSERT INTO Genres (genre_name) VALUES ('France');
INSERT INTO Genres (genre_name) VALUES ('Roman');
INSERT INTO Genres (genre_name) VALUES ('Literature');
INSERT INTO Genres (genre_name) VALUES ('Novels');
INSERT INTO Genres (genre_name) VALUES ('Historical Fiction');
INSERT INTO Genres (genre_name) VALUES ('Anthropology');
INSERT INTO Genres (genre_name) VALUES ('Sociology of Education');
INSERT INTO Genres (genre_name) VALUES ('Political Theory');
INSERT INTO Genres (genre_name) VALUES ('Games Theory');
INSERT INTO Genres (genre_name) VALUES ('Theory');
INSERT INTO Genres (genre_name) VALUES ('Class Conflict');
INSERT INTO Genres (genre_name) VALUES ('Marxism');
INSERT INTO Genres (genre_name) VALUES ('Social Conflict Theory');
INSERT INTO Genres (genre_name) VALUES ('Social Class');
INSERT INTO Genres (genre_name) VALUES ('Essays');
INSERT INTO Genres (genre_name) VALUES ('Italy');
INSERT INTO Genres (genre_name) VALUES ('Italian Literature');
INSERT INTO Genres (genre_name) VALUES ('European Literature');
INSERT INTO Genres (genre_name) VALUES ('Manual');
INSERT INTO Genres (genre_name) VALUES ('Essai');
INSERT INTO Genres (genre_name) VALUES ('Political theory');
INSERT INTO Genres (genre_name) VALUES ('Government');
INSERT INTO Genres (genre_name) VALUES ('Maths');
INSERT INTO Genres (genre_name) VALUES ('World Atlas');
INSERT INTO Genres (genre_name) VALUES ('Dictionary');
INSERT INTO Genres (genre_name) VALUES ('Language');
INSERT INTO Genres (genre_name) VALUES ('Russia');
INSERT INTO Genres (genre_name) VALUES ('Russian Literature');
INSERT INTO Genres (genre_name) VALUES ('Crime');
INSERT INTO Genres (genre_name) VALUES ('19th Century');
INSERT INTO Genres (genre_name) VALUES ('Mystery');
INSERT INTO Genres (genre_name) VALUES ('Mystery Thriller');
INSERT INTO Genres (genre_name) VALUES ('Detective');
INSERT INTO Genres (genre_name) VALUES ('British Literature');
INSERT INTO Genres (genre_name) VALUES ('Thriller');
INSERT INTO Genres (genre_name) VALUES ('Murder Mystery');
INSERT INTO Genres (genre_name) VALUES ('Suspense');
INSERT INTO Genres (genre_name) VALUES ('Pharmacology');
INSERT INTO Genres (genre_name) VALUES ('Essai Political Theory');
INSERT INTO Genres (genre_name) VALUES ('20th Century');
INSERT INTO Genres (genre_name) VALUES ('Criticism');
INSERT INTO Genres (genre_name) VALUES ('Activism');
INSERT INTO Genres (genre_name) VALUES ('Political Analysis');
INSERT INTO Genres (genre_name) VALUES ('Lenin');
INSERT INTO Genres (genre_name) VALUES ('Humanities');
INSERT INTO Genres (genre_name) VALUES ('Unionism');
INSERT INTO Genres (genre_name) VALUES ('European History');
INSERT INTO Genres (genre_name) VALUES ('Unfinished');
INSERT INTO Genres (genre_name) VALUES ('College');
INSERT INTO Genres (genre_name) VALUES ('Law');
INSERT INTO Genres (genre_name) VALUES ('Constitutional Law');
INSERT INTO Genres (genre_name) VALUES ('Self-Help');
INSERT INTO Genres (genre_name) VALUES ('Historical');
INSERT INTO Genres (genre_name) VALUES ('Adult');
INSERT INTO Genres (genre_name) VALUES ('Religion');
INSERT INTO Genres (genre_name) VALUES ('Theology');
INSERT INTO Genres (genre_name) VALUES ('Christianity');
INSERT INTO Genres (genre_name) VALUES ('Love');
INSERT INTO Genres (genre_name) VALUES ('Bioinformatics');
INSERT INTO Genres (genre_name) VALUES ('Mental Health');
INSERT INTO Genres (genre_name) VALUES ('Disability Studies');
INSERT INTO Genres (genre_name) VALUES ('Spirituality');
INSERT INTO Genres (genre_name) VALUES ('Linguistics');
INSERT INTO Genres (genre_name) VALUES ('Latin American History');
INSERT INTO Genres (genre_name) VALUES ('Germany');
INSERT INTO Genres (genre_name) VALUES ('Historical Mystery');
INSERT INTO Genres (genre_name) VALUES ('Ancient History');
INSERT INTO Genres (genre_name) VALUES ('Greece');
INSERT INTO Genres (genre_name) VALUES ('Ancient');
INSERT INTO Genres (genre_name) VALUES ('Mythology');
INSERT INTO Genres (genre_name) VALUES ('Poetry');
INSERT INTO Genres (genre_name) VALUES ('Literature.');
INSERT INTO Genres (genre_name) VALUES ('Non-fiction');
INSERT INTO Genres (genre_name) VALUES ('French Literature');
INSERT INTO Genres (genre_name) VALUES ('17th Century');
INSERT INTO Genres (genre_name) VALUES ('Atheism');
INSERT INTO Genres (genre_name) VALUES ('Memoir');
INSERT INTO Genres (genre_name) VALUES ('Holocaust');
INSERT INTO Genres (genre_name) VALUES ('Autobiography');
INSERT INTO Genres (genre_name) VALUES ('World War II');
INSERT INTO Genres (genre_name) VALUES ('Judaism');
INSERT INTO Genres (genre_name) VALUES ('Medieval');
INSERT INTO Genres (genre_name) VALUES ('Ancient Greece');
INSERT INTO Genres (genre_name) VALUES ('Writing');
INSERT INTO Genres (genre_name) VALUES ('India');
INSERT INTO Genres (genre_name) VALUES ('Race');
INSERT INTO Genres (genre_name) VALUES ('African American');
INSERT INTO Genres (genre_name) VALUES ('Theatre');
INSERT INTO Genres (genre_name) VALUES ('Drama');
INSERT INTO Genres (genre_name) VALUES ('Plays');
INSERT INTO Genres (genre_name) VALUES ('Adventure');
INSERT INTO Genres (genre_name) VALUES ('Fantasy');
INSERT INTO Genres (genre_name) VALUES ('Read For School');
INSERT INTO Genres (genre_name) VALUES ('Greek Mythology');
INSERT INTO Genres (genre_name) VALUES ('Life');
INSERT INTO Genres (genre_name) VALUES ('Christian');
INSERT INTO Genres (genre_name) VALUES ('Faith');
INSERT INTO Genres (genre_name) VALUES ('Christian Non Fiction');
INSERT INTO Genres (genre_name) VALUES ('Programming');
INSERT INTO Genres (genre_name) VALUES ('Technical');
INSERT INTO Genres (genre_name) VALUES ('Coding');
INSERT INTO Genres (genre_name) VALUES ('Legal Thriller');
INSERT INTO Genres (genre_name) VALUES ('Adult Fiction');
INSERT INTO Genres (genre_name) VALUES ('Business Management');
INSERT INTO Genres (genre_name) VALUES ('Emotional Intelligence');
INSERT INTO Genres (genre_name) VALUES ('Self-Help');
INSERT INTO Genres (genre_name) VALUES ('Programming');
INSERT INTO Genres (genre_name) VALUES ('Software Design Patterns');
INSERT INTO Genres (genre_name) VALUES ('Agile');
INSERT INTO Genres (genre_name) VALUES ('DevOps');
INSERT INTO Genres (genre_name) VALUES ('Event-driven Programming');
INSERT INTO Genres (genre_name) VALUES ('Web Services');
INSERT INTO Genres (genre_name) VALUES ('Continuos integration');
INSERT INTO Genres (genre_name) VALUES ('Business Analytics');
INSERT INTO Genres (genre_name) VALUES ('Functional Programming');
INSERT INTO Genres (genre_name) VALUES ('Historia');
INSERT INTO Genres (genre_name) VALUES ('Public Policy');
INSERT INTO Genres (genre_name) VALUES ('Cuisine');
INSERT INTO Genres (genre_name) VALUES ('Policital Science');
INSERT INTO Genres (genre_name) VALUES ('Snacks.');
INSERT INTO Genres (genre_name) VALUES ('Political Philosophy');
INSERT INTO Genres (genre_name) VALUES ('Psychoanalyse');
INSERT INTO Genres (genre_name) VALUES ('Geography');
INSERT INTO Genres (genre_name) VALUES ('Psychology;');
INSERT INTO Genres (genre_name) VALUES ('Sociologie');
INSERT INTO Genres (genre_name) VALUES ('Science Fiction');
INSERT INTO Genres (genre_name) VALUES ('Filosofía');
INSERT INTO Genres (genre_name) VALUES ('Tourism');
INSERT INTO Genres (genre_name) VALUES ('Fiction');
INSERT INTO Genres (genre_name) VALUES ('Dictionary');
INSERT INTO Genres (genre_name) VALUES ('Python');