INSERT INTO Genres (genre_id, genre_name) VALUES (1, 'Nonfiction');
INSERT INTO Genres (genre_id, genre_name) VALUES (2, 'Leadership');
INSERT INTO Genres (genre_id, genre_name) VALUES (3, 'Business');
INSERT INTO Genres (genre_id, genre_name) VALUES (4, 'Self Help');
INSERT INTO Genres (genre_id, genre_name) VALUES (5, 'Personal Development');
INSERT INTO Genres (genre_id, genre_name) VALUES (6, 'Psychology');
INSERT INTO Genres (genre_id, genre_name) VALUES (7, 'Management');
INSERT INTO Genres (genre_id, genre_name) VALUES (8, 'Education');
INSERT INTO Genres (genre_id, genre_name) VALUES (9, 'Philosophy');
INSERT INTO Genres (genre_id, genre_name) VALUES (10, 'Productivity');
INSERT INTO Genres (genre_id, genre_name) VALUES (11, 'History');
INSERT INTO Genres (genre_id, genre_name) VALUES (12, 'Personnel management');
INSERT INTO Genres (genre_id, genre_name) VALUES (13, 'War');
INSERT INTO Genres (genre_id, genre_name) VALUES (14, 'Politics');
INSERT INTO Genres (genre_id, genre_name) VALUES (15, 'Military Fiction');
INSERT INTO Genres (genre_id, genre_name) VALUES (16, 'Military History');
INSERT INTO Genres (genre_id, genre_name) VALUES (17, 'Economics');
INSERT INTO Genres (genre_id, genre_name) VALUES (18, 'Communication');
INSERT INTO Genres (genre_id, genre_name) VALUES (19, 'Design');
INSERT INTO Genres (genre_id, genre_name) VALUES (20, 'Audiobook');
INSERT INTO Genres (genre_id, genre_name) VALUES (21, 'Entrepreneurship');
INSERT INTO Genres (genre_id, genre_name) VALUES (22, 'Finance');
INSERT INTO Genres (genre_id, genre_name) VALUES (23, 'social sciences');
INSERT INTO Genres (genre_id, genre_name) VALUES (24, 'ethics');
INSERT INTO Genres (genre_id, genre_name) VALUES (25, 'socio-ecological crises');
INSERT INTO Genres (genre_id, genre_name) VALUES (26, 'political philosophy');
INSERT INTO Genres (genre_id, genre_name) VALUES (27, 'Sociology');
INSERT INTO Genres (genre_id, genre_name) VALUES (28, 'German Literature');
INSERT INTO Genres (genre_id, genre_name) VALUES (29, 'Psychoanalysis');
INSERT INTO Genres (genre_id, genre_name) VALUES (30, 'Classics');
INSERT INTO Genres (genre_id, genre_name) VALUES (31, 'Science');
INSERT INTO Genres (genre_id, genre_name) VALUES (32, 'Relationships');
INSERT INTO Genres (genre_id, genre_name) VALUES (33, 'How To');
INSERT INTO Genres (genre_id, genre_name) VALUES (34, 'Reference');
INSERT INTO Genres (genre_id, genre_name) VALUES (35, 'Artificial Intelligence');
INSERT INTO Genres (genre_id, genre_name) VALUES (36, 'Technology');
INSERT INTO Genres (genre_id, genre_name) VALUES (37, 'Futurism');
INSERT INTO Genres (genre_id, genre_name) VALUES (38, 'Computer Science');
INSERT INTO Genres (genre_id, genre_name) VALUES (39, 'Physics');
INSERT INTO Genres (genre_id, genre_name) VALUES (40, 'Social');
INSERT INTO Genres (genre_id, genre_name) VALUES (41, 'International Relations');
INSERT INTO Genres (genre_id, genre_name) VALUES (42, 'Political Science');
INSERT INTO Genres (genre_id, genre_name) VALUES (43, 'World History');
INSERT INTO Genres (genre_id, genre_name) VALUES (44, 'American History');
INSERT INTO Genres (genre_id, genre_name) VALUES (45, 'Informatics');
INSERT INTO Genres (genre_id, genre_name) VALUES (46, 'Software');
INSERT INTO Genres (genre_id, genre_name) VALUES (47, 'Microsoft');
INSERT INTO Genres (genre_id, genre_name) VALUES (48, 'Medicine');
INSERT INTO Genres (genre_id, genre_name) VALUES (49, 'Medical');
INSERT INTO Genres (genre_id, genre_name) VALUES (50, 'Textbooks');
INSERT INTO Genres (genre_id, genre_name) VALUES (51, 'Health');
INSERT INTO Genres (genre_id, genre_name) VALUES (52, 'Biology');
INSERT INTO Genres (genre_id, genre_name) VALUES (53, 'School');
INSERT INTO Genres (genre_id, genre_name) VALUES (54, 'Anatomy');
INSERT INTO Genres (genre_id, genre_name) VALUES (55, 'Anaesthesia');
INSERT INTO Genres (genre_id, genre_name) VALUES (56, 'Odontology');
INSERT INTO Genres (genre_id, genre_name) VALUES (57, 'Nursing');
INSERT INTO Genres (genre_id, genre_name) VALUES (58, 'Operating room');
INSERT INTO Genres (genre_id, genre_name) VALUES (59, 'Biochemistry');
INSERT INTO Genres (genre_id, genre_name) VALUES (60, 'Migration studies');
INSERT INTO Genres (genre_id, genre_name) VALUES (61, 'Healthcare');
INSERT INTO Genres (genre_id, genre_name) VALUES (62, 'Preventive Medicine');
INSERT INTO Genres (genre_id, genre_name) VALUES (63, 'Perioperative Nursing');
INSERT INTO Genres (genre_id, genre_name) VALUES (64, 'Languages');
INSERT INTO Genres (genre_id, genre_name) VALUES (65, 'French');
INSERT INTO Genres (genre_id, genre_name) VALUES (66, 'German');
INSERT INTO Genres (genre_id, genre_name) VALUES (67, 'Chemistry');
INSERT INTO Genres (genre_id, genre_name) VALUES (68, 'Operating Room');
INSERT INTO Genres (genre_id, genre_name) VALUES (69, 'Economy');
INSERT INTO Genres (genre_id, genre_name) VALUES (70, 'Political Economy');
INSERT INTO Genres (genre_id, genre_name) VALUES (71, 'Statistics');
INSERT INTO Genres (genre_id, genre_name) VALUES (72, 'Oral Microbiology');
INSERT INTO Genres (genre_id, genre_name) VALUES (73, 'Dentistry');
INSERT INTO Genres (genre_id, genre_name) VALUES (74, 'Sociology of Health');
INSERT INTO Genres (genre_id, genre_name) VALUES (75, 'Mathematics');
INSERT INTO Genres (genre_id, genre_name) VALUES (76, 'Popular Science');
INSERT INTO Genres (genre_id, genre_name) VALUES (77, 'Internal Medicine');
INSERT INTO Genres (genre_id, genre_name) VALUES (78, 'Computational Chemistry');
INSERT INTO Genres (genre_id, genre_name) VALUES (79, 'Academic');
INSERT INTO Genres (genre_id, genre_name) VALUES (80, 'Social Science');
INSERT INTO Genres (genre_id, genre_name) VALUES (81, 'Evolution');
INSERT INTO Genres (genre_id, genre_name) VALUES (82, 'Nature');
INSERT INTO Genres (genre_id, genre_name) VALUES (83, 'Quantum Mechanics');
INSERT INTO Genres (genre_id, genre_name) VALUES (84, 'Astronomy');
INSERT INTO Genres (genre_id, genre_name) VALUES (85, 'Space');
INSERT INTO Genres (genre_id, genre_name) VALUES (86, 'Engineering');
INSERT INTO Genres (genre_id, genre_name) VALUES (87, 'Science Textbooks');
INSERT INTO Genres (genre_id, genre_name) VALUES (88, 'Academic School');
INSERT INTO Genres (genre_id, genre_name) VALUES (89, 'Society');
INSERT INTO Genres (genre_id, genre_name) VALUES (90, 'Cultural');
INSERT INTO Genres (genre_id, genre_name) VALUES (91, 'Genomics');
INSERT INTO Genres (genre_id, genre_name) VALUES (92, 'Socialism');
INSERT INTO Genres (genre_id, genre_name) VALUES (93, 'II República');
INSERT INTO Genres (genre_id, genre_name) VALUES (94, 'Spain');
INSERT INTO Genres (genre_id, genre_name) VALUES (95, 'Spanish Literature');
INSERT INTO Genres (genre_id, genre_name) VALUES (96, 'Historical Memoir');
INSERT INTO Genres (genre_id, genre_name) VALUES (97, 'Latin American');
INSERT INTO Genres (genre_id, genre_name) VALUES (98, 'Biography');
INSERT INTO Genres (genre_id, genre_name) VALUES (99, 'Roman Empire');
INSERT INTO Genres (genre_id, genre_name) VALUES (100, 'Fiction');
INSERT INTO Genres (genre_id, genre_name) VALUES (101, 'France');
INSERT INTO Genres (genre_id, genre_name) VALUES (102, 'Roman');
INSERT INTO Genres (genre_id, genre_name) VALUES (103, 'Literature');
INSERT INTO Genres (genre_id, genre_name) VALUES (104, 'Novels');
INSERT INTO Genres (genre_id, genre_name) VALUES (105, 'Historical Fiction');
INSERT INTO Genres (genre_id, genre_name) VALUES (106, 'Anthropology');
INSERT INTO Genres (genre_id, genre_name) VALUES (107, 'Sociology of Education');
INSERT INTO Genres (genre_id, genre_name) VALUES (108, 'Political Theory');
INSERT INTO Genres (genre_id, genre_name) VALUES (109, 'Games Theory');
INSERT INTO Genres (genre_id, genre_name) VALUES (110, 'Theory');
INSERT INTO Genres (genre_id, genre_name) VALUES (111, 'Class Conflict');
INSERT INTO Genres (genre_id, genre_name) VALUES (112, 'Marxism');
INSERT INTO Genres (genre_id, genre_name) VALUES (113, 'Social Conflict Theory');
INSERT INTO Genres (genre_id, genre_name) VALUES (114, 'Social Class');
INSERT INTO Genres (genre_id, genre_name) VALUES (115, 'Essays');
INSERT INTO Genres (genre_id, genre_name) VALUES (116, 'Italy');
INSERT INTO Genres (genre_id, genre_name) VALUES (117, 'Italian Literature');
INSERT INTO Genres (genre_id, genre_name) VALUES (118, 'European Literature');
INSERT INTO Genres (genre_id, genre_name) VALUES (119, 'Manual');
INSERT INTO Genres (genre_id, genre_name) VALUES (120, 'Essai');
INSERT INTO Genres (genre_id, genre_name) VALUES (121, 'Political theory');
INSERT INTO Genres (genre_id, genre_name) VALUES (122, 'Government');
INSERT INTO Genres (genre_id, genre_name) VALUES (123, 'Maths');
INSERT INTO Genres (genre_id, genre_name) VALUES (124, 'World Atlas');
INSERT INTO Genres (genre_id, genre_name) VALUES (125, 'Dictionary');
INSERT INTO Genres (genre_id, genre_name) VALUES (126, 'Language');
INSERT INTO Genres (genre_id, genre_name) VALUES (127, 'Russia');
INSERT INTO Genres (genre_id, genre_name) VALUES (128, 'Russian Literature');
INSERT INTO Genres (genre_id, genre_name) VALUES (129, 'Crime');
INSERT INTO Genres (genre_id, genre_name) VALUES (130, '19th Century');
INSERT INTO Genres (genre_id, genre_name) VALUES (131, 'Mystery');
INSERT INTO Genres (genre_id, genre_name) VALUES (132, 'Mystery Thriller');
INSERT INTO Genres (genre_id, genre_name) VALUES (133, 'Detective');
INSERT INTO Genres (genre_id, genre_name) VALUES (134, 'British Literature');
INSERT INTO Genres (genre_id, genre_name) VALUES (135, 'Thriller');
INSERT INTO Genres (genre_id, genre_name) VALUES (136, 'Murder Mystery');
INSERT INTO Genres (genre_id, genre_name) VALUES (137, 'Suspense');
INSERT INTO Genres (genre_id, genre_name) VALUES (138, 'Pharmacology');
INSERT INTO Genres (genre_id, genre_name) VALUES (139, 'Essai Political Theory');
INSERT INTO Genres (genre_id, genre_name) VALUES (140, '20th Century');
INSERT INTO Genres (genre_id, genre_name) VALUES (141, 'Criticism');
INSERT INTO Genres (genre_id, genre_name) VALUES (142, 'Activism');
INSERT INTO Genres (genre_id, genre_name) VALUES (143, 'Political Analysis');
INSERT INTO Genres (genre_id, genre_name) VALUES (144, 'Lenin');
INSERT INTO Genres (genre_id, genre_name) VALUES (145, '');
INSERT INTO Genres (genre_id, genre_name) VALUES (146, 'Humanities');
INSERT INTO Genres (genre_id, genre_name) VALUES (147, 'Unionism');
INSERT INTO Genres (genre_id, genre_name) VALUES (148, 'European History');
INSERT INTO Genres (genre_id, genre_name) VALUES (149, 'Unfinished');
INSERT INTO Genres (genre_id, genre_name) VALUES (150, 'College');
INSERT INTO Genres (genre_id, genre_name) VALUES (151, 'Law');
INSERT INTO Genres (genre_id, genre_name) VALUES (152, 'Constitutional Law');
INSERT INTO Genres (genre_id, genre_name) VALUES (153, 'Self-Help');
INSERT INTO Genres (genre_id, genre_name) VALUES (154, 'Historical');
INSERT INTO Genres (genre_id, genre_name) VALUES (155, 'Adult');
INSERT INTO Genres (genre_id, genre_name) VALUES (156, 'Religion');
INSERT INTO Genres (genre_id, genre_name) VALUES (157, 'Theology');
INSERT INTO Genres (genre_id, genre_name) VALUES (158, 'Christianity');
INSERT INTO Genres (genre_id, genre_name) VALUES (159, 'Love');
INSERT INTO Genres (genre_id, genre_name) VALUES (160, 'Bioinformatics');
INSERT INTO Genres (genre_id, genre_name) VALUES (161, 'Mental Health');
INSERT INTO Genres (genre_id, genre_name) VALUES (162, 'Disability Studies');
INSERT INTO Genres (genre_id, genre_name) VALUES (163, 'Spirituality');
INSERT INTO Genres (genre_id, genre_name) VALUES (164, 'Linguistics');
INSERT INTO Genres (genre_id, genre_name) VALUES (165, 'Latin American History');
INSERT INTO Genres (genre_id, genre_name) VALUES (166, 'Germany');
INSERT INTO Genres (genre_id, genre_name) VALUES (167, 'Historical Mystery');
INSERT INTO Genres (genre_id, genre_name) VALUES (168, 'Ancient History');
INSERT INTO Genres (genre_id, genre_name) VALUES (169, 'Greece');
INSERT INTO Genres (genre_id, genre_name) VALUES (170, 'Ancient');
INSERT INTO Genres (genre_id, genre_name) VALUES (171, 'Mythology');
INSERT INTO Genres (genre_id, genre_name) VALUES (172, 'Poetry');
INSERT INTO Genres (genre_id, genre_name) VALUES (173, 'Literature.');
INSERT INTO Genres (genre_id, genre_name) VALUES (174, 'Non-fiction');
INSERT INTO Genres (genre_id, genre_name) VALUES (175, 'French Literature');
INSERT INTO Genres (genre_id, genre_name) VALUES (176, '17th Century');
INSERT INTO Genres (genre_id, genre_name) VALUES (177, 'Atheism');
INSERT INTO Genres (genre_id, genre_name) VALUES (178, 'Memoir');
INSERT INTO Genres (genre_id, genre_name) VALUES (179, 'Holocaust');
INSERT INTO Genres (genre_id, genre_name) VALUES (180, 'Autobiography');
INSERT INTO Genres (genre_id, genre_name) VALUES (181, 'World War II');
INSERT INTO Genres (genre_id, genre_name) VALUES (182, 'Judaism');
INSERT INTO Genres (genre_id, genre_name) VALUES (183, 'Medieval');
INSERT INTO Genres (genre_id, genre_name) VALUES (184, 'Ancient Greece');
INSERT INTO Genres (genre_id, genre_name) VALUES (185, 'Writing');
INSERT INTO Genres (genre_id, genre_name) VALUES (186, 'India');
INSERT INTO Genres (genre_id, genre_name) VALUES (187, 'Race');
INSERT INTO Genres (genre_id, genre_name) VALUES (188, 'African American');
INSERT INTO Genres (genre_id, genre_name) VALUES (189, 'Theatre');
INSERT INTO Genres (genre_id, genre_name) VALUES (190, 'Drama');
INSERT INTO Genres (genre_id, genre_name) VALUES (191, 'Plays');
INSERT INTO Genres (genre_id, genre_name) VALUES (192, 'Adventure');
INSERT INTO Genres (genre_id, genre_name) VALUES (193, 'Fantasy');
INSERT INTO Genres (genre_id, genre_name) VALUES (194, 'Read For School');
INSERT INTO Genres (genre_id, genre_name) VALUES (195, 'Greek Mythology');
INSERT INTO Genres (genre_id, genre_name) VALUES (196, 'Life');
INSERT INTO Genres (genre_id, genre_name) VALUES (197, 'Christian');
INSERT INTO Genres (genre_id, genre_name) VALUES (198, 'Faith');
INSERT INTO Genres (genre_id, genre_name) VALUES (199, 'Christian Non Fiction');
INSERT INTO Genres (genre_id, genre_name) VALUES (200, 'Programming');
INSERT INTO Genres (genre_id, genre_name) VALUES (201, 'Technical');
INSERT INTO Genres (genre_id, genre_name) VALUES (202, 'Coding');
INSERT INTO Genres (genre_id, genre_name) VALUES (203, 'Legal Thriller');
INSERT INTO Genres (genre_id, genre_name) VALUES (204, 'Adult Fiction');
INSERT INTO Genres (genre_id, genre_name) VALUES (205, 'n');
INSERT INTO Genres (genre_id, genre_name) VALUES (206, 'cccc');
INSERT INTO Genres (genre_id, genre_name) VALUES (207, 'Business Management');
INSERT INTO Genres (genre_id, genre_name) VALUES (208, 'Emotional Intelligence');
INSERT INTO Genres (genre_id, genre_name) VALUES (209, 'SElf-Help');
INSERT INTO Genres (genre_id, genre_name) VALUES (210, 'Historia');
INSERT INTO Genres (genre_id, genre_name) VALUES (211, 'Sociology; Public Policy');
INSERT INTO Genres (genre_id, genre_name) VALUES (212, 'Cuisine');
INSERT INTO Genres (genre_id, genre_name) VALUES (213, 'Policital Science');
INSERT INTO Genres (genre_id, genre_name) VALUES (214, 'Essai.');
INSERT INTO Genres (genre_id, genre_name) VALUES (215, 'Political Philosophy');
INSERT INTO Genres (genre_id, genre_name) VALUES (216, 'Psychoanalyse');
INSERT INTO Genres (genre_id, genre_name) VALUES (217, 'Tourism; Geography');
INSERT INTO Genres (genre_id, genre_name) VALUES (218, 'War; History');
INSERT INTO Genres (genre_id, genre_name) VALUES (219, 'Essai; Sociology; Health');
INSERT INTO Genres (genre_id, genre_name) VALUES (220, 'Science; Sociology');
INSERT INTO Genres (genre_id, genre_name) VALUES (221, 'Psychology;');
INSERT INTO Genres (genre_id, genre_name) VALUES (222, 'Essai; Sociology; Economics; History');
INSERT INTO Genres (genre_id, genre_name) VALUES (223, 'Sociologie');
INSERT INTO Genres (genre_id, genre_name) VALUES (224, 'Science Fiction');
INSERT INTO Genres (genre_id, genre_name) VALUES (225, 'Fiction; History');
INSERT INTO Genres (genre_id, genre_name) VALUES (226, 'Filosofía');
INSERT INTO Genres (genre_id, genre_name) VALUES (227, 'Python');
INSERT INTO Genres (genre_id, genre_name) VALUES (228, 'Sociology; Philosophy');
INSERT INTO Genres (genre_id, genre_name) VALUES (229, 'Tourism');
INSERT INTO Genres (genre_id, genre_name) VALUES (230, 'FIction');
INSERT INTO Genres (genre_id, genre_name) VALUES (231, 'Sociology; Nursing');
INSERT INTO Genres (genre_id, genre_name) VALUES (232, 'Sociology; Religion');